function fg = fig_setting_default()

% figure style
fg.fsz = 20;      % Fontsize
fg.lw = 2.5;      % LineWidth
fg.msz = 10;       % MarkerSize

fg.pu = get(gcf,'PaperUnits');
fg.pp = get(gcf,'PaperPosition');

set(gcf,...
    'Units',fg.pu,...
    'Position',fg.pp,...
    'PaperPosition', fg.pp,...
    'color', 'w'...
    );
set(gca,...
    'box','off',...
    'layer','top',...
    'TickDir','out',...
    'FontSize', fg.fsz,...
    'LineWidth', fg.lw...
    );